# mkdir -p $HOME/Library/Application\ Support/jesseduffield
# ln -s $HOME/4_pub/github/dots/lazydocker $HOME/Library/Application\ Support/jesseduffield

gui:
  scrollHeight: 2
  language: auto
  theme:
    activeBorderColor:
    - green
    - bold
    inactiveBorderColor:
    - default
    selectedLineBgColor:
    - blue
    optionsTextColor:
    - blue
  wrapMainPanel: true
  sidePanelWidth: 0.3333
  showBottomLine: true
  expandFocusedSidePanel: false
  screenMode: normal
  containerStatusHealthStyle: long
  border: ""
logs:
  since: 60m
commandTemplates:
  restartService: '{{ .DockerCompose }} restart {{ .Service.Name }}'
  startService: '{{ .DockerCompose }} start {{ .Service.Name }}'
  upService: '{{ .DockerCompose }} up -d {{ .Service.Name }}'
  up: '{{ .DockerCompose }} up -d'
  down: '{{ .DockerCompose }} down'
  downWithVolumes: '{{ .DockerCompose }} down --volumes'
  dockerCompose: docker compose
  stopService: '{{ .DockerCompose }} stop {{ .Service.Name }}'
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  viewServiceLogs: '{{ .DockerCompose }} logs --follow {{ .Service.Name }}'
  rebuildService: '{{ .DockerCompose }} up -d --build {{ .Service.Name }}'
  recreateService: '{{ .DockerCompose }} up -d --force-recreate {{ .Service.Name }}'
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow'
  viewAlLogs: '{{ .DockerCompose }} logs'
  dockerComposeConfig: '{{ .DockerCompose }} config'
  checkDockerComposeConfig: '{{ .DockerCompose }} config --quiet'
  serviceTop: '{{ .DockerCompose }} top {{ .Service.Name }}'
bulkCommands:
  services:
  - name: up
    attach: false
    shell: false
    command: '{{ .DockerCompose }} up -d'
    serviceNames: []
  - name: up (attached)
    attach: true
    shell: false
    command: '{{ .DockerCompose }} up'
    serviceNames: []
  - name: stop
    attach: false
    shell: false
    command: '{{ .DockerCompose }} stop'
    serviceNames: []
  - name: pull
    attach: true
    shell: false
    command: '{{ .DockerCompose }} pull'
    serviceNames: []
  - name: build
    attach: true
    shell: false
    command: '{{ .DockerCompose }} build --parallel --force-rm'
    serviceNames: []
  - name: down
    attach: false
    shell: false
    command: '{{ .DockerCompose }} down'
    serviceNames: []
  - name: down with volumes
    attach: false
    shell: false
    command: '{{ .DockerCompose }} down --volumes'
    serviceNames: []
  - name: down with images
    attach: false
    shell: false
    command: '{{ .DockerCompose }} down --rmi all'
    serviceNames: []
  - name: down with volumes and images
    attach: false
    shell: false
    command: '{{ .DockerCompose }} down --volumes --rmi all'
    serviceNames: []
oS:
  openCommand: open {{filename}}
  openLinkCommand: open {{link}}
stats:
  graphs:
  - caption: CPU (%)
    statPath: DerivedStats.CPUPercentage
    color: cyan
  - caption: Memory (%)
    statPath: DerivedStats.MemoryPercentage
    color: green
  maxDuration: 3m0s
customCommands:
  containers:
    - name: bash
      attach: true
      command: docker exec -it {{ .Container.ID }} bash
      serviceNames: []
    - name: sh
      attach: true
      command: docker exec -it {{ .Container.ID }} sh
      serviceNames: []
  images:
    - name: bash
      attach: true
      command: docker run -it --rm --entrypoint bash {{ .Image.ID }}
      serviceNames: []
    - name: bash (amd64)
      attach: true
      command: DOCKER_DEFAULT_PLATFORM=linux/amd64 docker run -it --rm --entrypoint bash {{ .Image.ID }}
      serviceNames: []
    - name: sh
      attach: true
      command: docker run -it --rm --entrypoint sh {{ .Image.ID }}
      serviceNames: []
    - name: sh (amd64)
      attach: true
      command: DOCKER_DEFAULT_PLATFORM=linux/amd64 docker run -it --rm --entrypoint sh {{ .Image.ID }}
      serviceNames: []
    - name: dive
      attach: true
      command: dive {{ .Image.ID }}
      serviceNames: []
